export default {
  products: [
    {
      id: 1,
      name: 'Slim Shirt',
      category: 'Shirts',
      image: '/images/d1.jpg',
      price: 60,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
    },
    {
      id: 2,
      name: 'Fit Shirt',
      category: 'Shirts',
      image: '/images/d1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.2,
      numReviews: 15,
    },
    {
      id: 3,
      name: 'Best Pants',
      category: 'Pants',
      image: '/images/d1.jpg',
      price: 30,
      brand: 'Nike',
      rating: 4.7,
      numReviews: 45,
    },
    {
      id: 4,
      name: 'Slim Shirt',
      category: 'Shirts',
      image: '/images/d1.jpg',
      price: 60,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
    },
    {
      id: 5,
      name: 'Fit Shirt',
      category: 'Shirts',
      image: '/images/d1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.2,
      numReviews: 15,
    },
    {
      id: 6,
      name: 'Best Pants',
      category: 'Pants',
      image: '/images/d1.jpg',
      price: 30,
      brand: 'Nike',
      rating: 4.7,
      numReviews: 45,
    },
  ],
};
